export const TODO_INIT = 'TODO_INIT';
export const TODO_COMPLETE = 'TODO_COMPLETE';
export const TODO_DELETE = 'TODO_DELETE';
export const TODO_SUBMIT = 'TODO_SUBMIT';
export const TODO_FILTER_ALL = 'TODO_FILTER_ALL';
export const TODO_FILTER_COMPLETE = 'TODO_FILTER_COMPLETE';
export const TODO_FILTER_ACTIVE = 'TODO_FILTER_ACTIVE';
